Nombre: cheque
en:
  workflow_dispatch:
  pull_request:
    Tipos: [abierto, sincronizar, volver a abrir, editar]
Simultaneidad:
  Grupo: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  Cancelación en curso: true
Puestos de trabajo:
  Comprobar:
    Se ejecuta: ubuntu-latest
    Pasos:
      - Usos: Acciones/checkout@v3
        con:
          fetch-depth: 2
      - Usos: tj-actions/changed-files@v35
        ID: Archivos
        con:
          Archivos: streams/*.m3u
      - Usos: Actions/Setup-node@v3
        if: ${{ !env. ACT && steps.files.outputs.any_changed == 'true' }}
        con:
          versión del nodo: 18
          Caché: 'npm'
      - Nombre: Instalar dependencias
        if: steps.files.outputs.any_changed == 'verdadero'
        Ejecutar: Instalación de npm
      - Nombre: Validar
        if: steps.files.outputs.any_changed == 'verdadero'
        Ejecutar: |
          npm run playlist:lint -- ${{ steps.files.outputs.all_changed_files }}
          npm run playlist:validate -- ${{ steps.files.outputs.all_changed_files }}
